/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.fpfomento.android_app.api.models

import com.fpfomento.android_app.api.models.ReportResponse

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param page 
 * @param pageSize 
 * @param reports 
 */


data class PaginatedReportsResponse (

    @Json(name = "page")
    val page: kotlin.Int,

    @Json(name = "page_size")
    val pageSize: kotlin.Int,

    @Json(name = "reports")
    val reports: kotlin.collections.List<ReportResponse>

) {


}

