/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.fpfomento.android_app.api.models

import com.fpfomento.android_app.api.models.ReportPriority
import com.fpfomento.android_app.api.models.ReportStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param title 
 * @param description 
 * @param latitude 
 * @param longitude 
 * @param status 
 * @param priority 
 * @param categoryId 
 * @param resolvedById 
 */


data class ReportUpdate (

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "latitude")
    val latitude: java.math.BigDecimal? = null,

    @Json(name = "longitude")
    val longitude: java.math.BigDecimal? = null,

    @Json(name = "status")
    val status: ReportStatus? = null,

    @Json(name = "priority")
    val priority: ReportPriority? = null,

    @Json(name = "categoryId")
    val categoryId: kotlin.Int? = null,

    @Json(name = "resolvedById")
    val resolvedById: kotlin.Int? = null

) {


}

