/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.fpfomento.android_app.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.fpfomento.android_app.api.apis.AuthApi
import com.fpfomento.android_app.api.models.HTTPValidationError
import com.fpfomento.android_app.api.models.LoginResponse
import com.fpfomento.android_app.api.models.UserLogin
import com.fpfomento.android_app.api.models.UserResponse

class AuthApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuthApi
        //val apiInstance = AuthApi()

        // to test authLoginAuthLoginPost
        should("test authLoginAuthLoginPost") {
            // uncomment below to test authLoginAuthLoginPost
            //val userLogin : UserLogin =  // UserLogin | 
            //val result : LoginResponse = apiInstance.authLoginAuthLoginPost(userLogin)
            //result shouldBe ("TODO")
        }

        // to test authRefreshAuthRefreshPost
        should("test authRefreshAuthRefreshPost") {
            // uncomment below to test authRefreshAuthRefreshPost
            //val result : LoginResponse = apiInstance.authRefreshAuthRefreshPost()
            //result shouldBe ("TODO")
        }

        // to test getMeAuthMeGet
        should("test getMeAuthMeGet") {
            // uncomment below to test getMeAuthMeGet
            //val result : UserResponse = apiInstance.getMeAuthMeGet()
            //result shouldBe ("TODO")
        }

    }
}
