/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.fpfomento.android_app.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.fpfomento.android_app.api.apis.ReportsApi
import com.fpfomento.android_app.api.models.HTTPValidationError
import com.fpfomento.android_app.api.models.PaginatedReportsResponse
import com.fpfomento.android_app.api.models.ReportCreate
import com.fpfomento.android_app.api.models.ReportResponse
import com.fpfomento.android_app.api.models.ReportUpdate

class ReportsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReportsApi
        //val apiInstance = ReportsApi()

        // to test createReportReportsPost
        should("test createReportReportsPost") {
            // uncomment below to test createReportReportsPost
            //val reportCreate : ReportCreate =  // ReportCreate | 
            //val result : ReportResponse = apiInstance.createReportReportsPost(reportCreate)
            //result shouldBe ("TODO")
        }

        // to test getReportReportsReportIdGet
        should("test getReportReportsReportIdGet") {
            // uncomment below to test getReportReportsReportIdGet
            //val reportId : kotlin.Int = 56 // kotlin.Int | 
            //val result : ReportResponse = apiInstance.getReportReportsReportIdGet(reportId)
            //result shouldBe ("TODO")
        }

        // to test getReportsReportsGet
        should("test getReportsReportsGet") {
            // uncomment below to test getReportsReportsGet
            //val page : kotlin.Int = 56 // kotlin.Int | Pagina actual
            //val pageSize : kotlin.Int = 56 // kotlin.Int | Cantidad de registros por pagina
            //val result : PaginatedReportsResponse = apiInstance.getReportsReportsGet(page, pageSize)
            //result shouldBe ("TODO")
        }

        // to test updateReportReportsReportIdPatch
        should("test updateReportReportsReportIdPatch") {
            // uncomment below to test updateReportReportsReportIdPatch
            //val reportId : kotlin.Int = 56 // kotlin.Int | 
            //val reportUpdate : ReportUpdate =  // ReportUpdate | 
            //val result : ReportResponse = apiInstance.updateReportReportsReportIdPatch(reportId, reportUpdate)
            //result shouldBe ("TODO")
        }

    }
}
