/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.fpfomento.android_app.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.fpfomento.android_app.api.models.HTTPValidationError
import com.fpfomento.android_app.api.models.ValidationError

class HTTPValidationErrorTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of HTTPValidationError
        //val modelInstance = HTTPValidationError()

        // to test the property `detail`
        should("test detail") {
            // uncomment below to test the property
            //modelInstance.detail shouldBe ("TODO")
        }

    }
}
