/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.fpfomento.android_app.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.fpfomento.android_app.api.models.PaginatedReportsResponse
import com.fpfomento.android_app.api.models.ReportResponse

class PaginatedReportsResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaginatedReportsResponse
        //val modelInstance = PaginatedReportsResponse()

        // to test the property `page`
        should("test page") {
            // uncomment below to test the property
            //modelInstance.page shouldBe ("TODO")
        }

        // to test the property `pageSize`
        should("test pageSize") {
            // uncomment below to test the property
            //modelInstance.pageSize shouldBe ("TODO")
        }

        // to test the property `reports`
        should("test reports") {
            // uncomment below to test the property
            //modelInstance.reports shouldBe ("TODO")
        }

    }
}
