/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.fpfomento.android_app.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.fpfomento.android_app.api.models.UserRole

class UserRoleTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserRole
        //val modelInstance = UserRole()

    }
}
