/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.fpfomento.android_app.api.models

import com.fpfomento.android_app.api.models.ReportPriority

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.math.BigDecimal

/**
 * 
 *
 * @param title 
 * @param description 
 * @param latitude 
 * @param longitude 
 * @param categoryId 
 * @param userId 
 * @param priority 
 */

@JsonClass(generateAdapter = true)

data class ReportCreate (

    @Json(name = "title")
    val title: String,

    @Json(name = "description")
    val description: String,

    @Json(name = "latitude")
    val latitude: BigDecimal,

    @Json(name = "longitude")
    val longitude: BigDecimal,

    @Json(name = "categoryId")
    val categoryId: Int,

    @Json(name = "userId")
    val userId: Int,

    @Json(name = "priority")
    val priority: ReportPriority? = null

) {


}

