/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.fpfomento.android_app.api.models

import com.fpfomento.android_app.api.models.ReportPriority
import com.fpfomento.android_app.api.models.ReportStatus
import com.fpfomento.android_app.api.models.UserBasicResponse

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.math.BigDecimal
import java.time.OffsetDateTime

/**
 * 
 *
 * @param id 
 * @param title 
 * @param description 
 * @param latitude 
 * @param longitude 
 * @param status 
 * @param priority 
 * @param userId 
 * @param resolvedById 
 * @param categoryId 
 * @param createdAt 
 * @param updatedAt 
 * @param user 
 * @param resolvedBy 
 */

@JsonClass(generateAdapter = true)

data class ReportResponse (

    @Json(name = "id")
    val id: Int,

    @Json(name = "title")
    val title: String,

    @Json(name = "description")
    val description: String,

    @Json(name = "latitude")
    val latitude: Double,

    @Json(name = "longitude")
    val longitude: Double,

    @Json(name = "status")
    val status: ReportStatus,

    @Json(name = "priority")
    val priority: ReportPriority,

    @Json(name = "userId")
    val userId: Int,

    @Json(name = "resolvedById")
    val resolvedById: Int?,

    @Json(name = "categoryId")
    val categoryId: Int,

    @Json(name = "createdAt")
    val createdAt: String,

    @Json(name = "updatedAt")
    val updatedAt: String,

    @Json(name = "user")
    val user: UserBasicResponse? = null,

    @Json(name = "resolvedBy")
    val resolvedBy: UserBasicResponse? = null

) {


}

