/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.fpfomento.android_app.api.models

import com.fpfomento.android_app.api.models.UserRole

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.time.OffsetDateTime

/**
 * 
 *
 * @param id 
 * @param username 
 * @param email 
 * @param role 
 * @param isActive 
 * @param points 
 * @param createdAt 
 */

@JsonClass(generateAdapter = true)

data class UserResponse (

    @Json(name = "id")
    val id: Int,

    @Json(name = "username")
    val username: String,

    @Json(name = "email")
    val email: String,

    @Json(name = "role")
    val role: UserRole,

    @Json(name = "isActive")
    val isActive: Boolean,

    @Json(name = "points")
    val points: Int,

    @Json(name = "createdAt")
    val createdAt: OffsetDateTime

) {


}

