/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.fpfomento.android_app.api.models

import com.fpfomento.android_app.api.models.LocationInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param loc 
 * @param msg 
 * @param type 
 * @param input 
 * @param ctx 
 */

@JsonClass(generateAdapter = true)

data class ValidationError (

    @Json(name = "loc")
    val loc: List<LocationInner>,

    @Json(name = "msg")
    val msg: String,

    @Json(name = "type")
    val type: String,

    @Json(name = "input")
    val input: Any? = null,

    @Json(name = "ctx")
    val ctx: Any? = null

) {


}

